# Stage 1: download dependencies and build target (static files in dist/)
FROM node:22-alpine3.23 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --quiet

COPY . .
RUN npm run build

# Stage 2: start nginx production server
FROM nginx:1.28.1-alpine3.23

LABEL org.opencontainers.image.authors="l.cicchino@unimolt.it"

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]