# Stage 1: download dependencies and build target (.jre)
FROM maven:3.9.12-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY checkstyle.xml .

COPY src ./src
RUN mvn package -DskipTests

# Stage 2: run app (with user account)
FROM eclipse-temurin:21-jre-alpine-3.23
WORKDIR /app

LABEL org.opencontainers.image.authors="l.cicchino@unimolt.it"

RUN adduser -D spring
USER spring

COPY --from=build /app/target/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]