# Stage 1: download dependencies and build target (.jar)
FROM maven:3.9.12-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B -q

COPY checkstyle.xml .

COPY src ./src
RUN mvn package -DskipTests -B -q

# Stage 2: run application using JRE and non-root user
FROM eclipse-temurin:21.0.9_10-jre-alpine-3.23
WORKDIR /app

LABEL org.opencontainers.image.authors="l.cicchino@unimolt.it"

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=build --chown=spring:spring /app/target/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]